export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "US" },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US" },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US" },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "US" },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US" },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
  { iata: "MCO", name: "Orlando International", city: "Orlando", country: "US" },
  { iata: "EWR", name: "Newark Liberty International", city: "Newark", country: "US" },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "US" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "US" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "US" },
  { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "US" },
  { iata: "LGA", name: "LaGuardia", city: "New York", country: "US" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "US" },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "US" },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington", country: "US" },
  { iata: "IAD", name: "Washington Dulles International", city: "Washington", country: "US" },
  { iata: "MDW", name: "Chicago Midway International", city: "Chicago", country: "US" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US" },
  { iata: "SAN", name: "San Diego International", city: "San Diego", country: "US" },
  { iata: "TPA", name: "Tampa International", city: "Tampa", country: "US" },
  { iata: "PDX", name: "Portland International", city: "Portland", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "US" },
  { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "US" },
  { iata: "OAK", name: "Oakland International", city: "Oakland", country: "US" },
  { iata: "SJC", name: "Norman Y. Mineta San Jose International", city: "San Jose", country: "US" },
  { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "US" },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", country: "US" },
  { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "US" },
  { iata: "BNA", name: "Nashville International", city: "Nashville", country: "US" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "US" },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "US" },
  { iata: "SNA", name: "John Wayne Airport – Orange County", city: "Santa Ana", country: "US" },
  { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "US" },
  { iata: "BDL", name: "Bradley International", city: "Hartford", country: "US" },
  { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "US" },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "US" },
  { iata: "TUS", name: "Tucson International", city: "Tucson", country: "US" },
  { iata: "ONT", name: "Ontario International", city: "Ontario", country: "US" },
  { iata: "RIC", name: "Richmond International", city: "Richmond", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", country: "US" },
  { iata: "OGG", name: "Kahului Airport", city: "Maui", country: "US" },
  { iata: "KOA", name: "Ellison Onizuka Kona International", city: "Kona", country: "US" },
  { iata: "LIH", name: "Lihue Airport", city: "Kauai", country: "US" },
  { iata: "GEG", name: "Spokane International", city: "Spokane", country: "US" },
  { iata: "ALB", name: "Albany International", city: "Albany", country: "US" },
  { iata: "ROC", name: "Frederick Douglass/Greater Rochester International", city: "Rochester", country: "US" },
  { iata: "ORF", name: "Norfolk International", city: "Norfolk", country: "US" },
  { iata: "GSO", name: "Piedmont Triad International", city: "Greensboro", country: "US" },
  { iata: "CHS", name: "Charleston International", city: "Charleston", country: "US" },
  { iata: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", country: "US" },
  { iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "US" },
  { iata: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "US" },
  { iata: "SJU", name: "Luis Muñoz Marín International", city: "San Juan", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "US" },
  { iata: "FAI", name: "Fairbanks International", city: "Fairbanks", country: "US" },
  { iata: "ELP", name: "El Paso International", city: "El Paso", country: "US" },
  { iata: "LBB", name: "Lubbock Preston Smith International", city: "Lubbock", country: "US" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", country: "US" },
  { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "US" },
  { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "US" },
  { iata: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", country: "US" },
  { iata: "CAE", name: "Columbia Metropolitan", city: "Columbia", country: "US" },
  { iata: "PNS", name: "Pensacola International", city: "Pensacola", country: "US" },
  { iata: "DSM", name: "Des Moines International", city: "Des Moines", country: "US" },
  { iata: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", country: "US" },
  { iata: "TUL", name: "Tulsa International", city: "Tulsa", country: "US" },
  { iata: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", country: "US" },
  { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "US" },
  { iata: "XNA", name: "Northwest Arkansas National", city: "Bentonville", country: "US" },
  { iata: "CRP", name: "Corpus Christi International", city: "Corpus Christi", country: "US" },
  { iata: "GPT", name: "Gulfport-Biloxi International", city: "Gulfport", country: "US" },
  { iata: "MHT", name: "Manchester-Boston Regional", city: "Manchester", country: "US" },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", country: "US" },
  { iata: "BTV", name: "Burlington International", city: "Burlington", country: "US" },
  { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", country: "US" },
  { iata: "LEX", name: "Blue Grass Airport", city: "Lexington", country: "US" },
  { iata: "EVV", name: "Evansville Regional", city: "Evansville", country: "US" },
  { iata: "SBN", name: "South Bend International", city: "South Bend", country: "US" },
  { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", country: "US" },
  { iata: "LAN", name: "Capital Region International", city: "Lansing", country: "US" },
  { iata: "CAK", name: "Akron-Canton Airport", city: "Akron", country: "US" },
  { iata: "TOL", name: "Eugene F. Kranz Toledo Express", city: "Toledo", country: "US" },
  { iata: "DAY", name: "James M. Cox Dayton International", city: "Dayton", country: "US" },
  { iata: "GRB", name: "Green Bay Austin Straubel International", city: "Green Bay", country: "US" },
  { iata: "MSN", name: "Dane County Regional", city: "Madison", country: "US" },
  { iata: "RST", name: "Rochester International", city: "Rochester", country: "US" },
  { iata: "FSD", name: "Sioux Falls Regional", city: "Sioux Falls", country: "US" },
  { iata: "BIS", name: "Bismarck Municipal", city: "Bismarck", country: "US" },
  { iata: "FAR", name: "Hector International", city: "Fargo", country: "US" },
  { iata: "RAP", name: "Rapid City Regional", city: "Rapid City", country: "US" },
  { iata: "GJT", name: "Grand Junction Regional", city: "Grand Junction", country: "US" },
  { iata: "MTJ", name: "Montrose Regional", city: "Montrose", country: "US" },
  { iata: "EGE", name: "Eagle County Regional", city: "Vail", country: "US" },
  { iata: "ASE", name: "Aspen/Pitkin County", city: "Aspen", country: "US" },
  { iata: "HDN", name: "Yampa Valley Regional", city: "Steamboat Springs", country: "US" },
  { iata: "RNO", name: "Reno-Tahoe International", city: "Reno", country: "US" },
  { iata: "LGB", name: "Long Beach Airport", city: "Long Beach", country: "US" },
  { iata: "BUR", name: "Hollywood Burbank Airport", city: "Burbank", country: "US" },
  { iata: "PSP", name: "Palm Springs International", city: "Palm Springs", country: "US" },
  { iata: "SBA", name: "Santa Barbara Airport", city: "Santa Barbara", country: "US" },
  { iata: "MRY", name: "Monterey Regional", city: "Monterey", country: "US" },
  { iata: "SBP", name: "San Luis Obispo County Regional", city: "San Luis Obispo", country: "US" },
  { iata: "FAT", name: "Fresno Yosemite International", city: "Fresno", country: "US" },
  { iata: "BFL", name: "Meadows Field", city: "Bakersfield", country: "US" },
  { iata: "CIC", name: "Chico Municipal", city: "Chico", country: "US" },
  { iata: "MFR", name: "Rogue Valley International-Medford", city: "Medford", country: "US" },
  { iata: "EUG", name: "Eugene Airport", city: "Eugene", country: "US" },
  { iata: "RDM", name: "Redmond Airport", city: "Bend", country: "US" },
  { iata: "YUM", name: "Yuma International", city: "Yuma", country: "US" },
  { iata: "FLG", name: "Flagstaff Pulliam Airport", city: "Flagstaff", country: "US" },
  { iata: "PIE", name: "St. Pete-Clearwater International", city: "Clearwater", country: "US" },
  { iata: "SRQ", name: "Sarasota-Bradenton International", city: "Sarasota", country: "US" },
  { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "US" },
  { iata: "VPS", name: "Destin-Fort Walton Beach Airport", city: "Fort Walton Beach", country: "US" },
  { iata: "MGM", name: "Montgomery Regional", city: "Montgomery", country: "US" },
  { iata: "MOB", name: "Mobile Regional", city: "Mobile", country: "US" },
  { iata: "HRL", name: "Valley International", city: "Harlingen", country: "US" },
  { iata: "MFE", name: "McAllen Miller International", city: "McAllen", country: "US" },
  { iata: "ACT", name: "Waco Regional", city: "Waco", country: "US" },
  { iata: "ABI", name: "Abilene Regional", city: "Abilene", country: "US" },
  { iata: "AMA", name: "Rick Husband Amarillo International", city: "Amarillo", country: "US" },
  { iata: "SPS", name: "Wichita Falls Municipal", city: "Wichita Falls", country: "US" },
  // Canada
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "CA" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA" },
  { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "CA" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "CA" },
  { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "CA" },
  { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "CA" },
  { iata: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", country: "CA" },
  { iata: "YQB", name: "Québec City Jean Lesage International", city: "Quebec City", country: "CA" },
  { iata: "YXE", name: "Saskatoon John G. Diefenbaker International", city: "Saskatoon", country: "CA" },
  // UK & Ireland
  { iata: "LHR", name: "London Heathrow", city: "London", country: "GB" },
  { iata: "LGW", name: "London Gatwick", city: "London", country: "GB" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "GB" },
  { iata: "STN", name: "London Stansted", city: "London", country: "GB" },
  { iata: "LTN", name: "London Luton", city: "London", country: "GB" },
  { iata: "LCY", name: "London City Airport", city: "London", country: "GB" },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "GB" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "GB" },
  { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "GB" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "IE" },
  { iata: "SNN", name: "Shannon Airport", city: "Shannon", country: "IE" },
  // Europe
  { iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "FR" },
  { iata: "ORY", name: "Paris Orly Airport", city: "Paris", country: "FR" },
  { iata: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "FR" },
  { iata: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "FR" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "DE" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "DE" },
  { iata: "TXL", name: "Berlin Tegel Airport", city: "Berlin", country: "DE" },
  { iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "DE" },
  { iata: "DUS", name: "Düsseldorf Airport", city: "Dusseldorf", country: "DE" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "DE" },
  { iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "DE" },
  { iata: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "DE" },
  { iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "NL" },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "ES" },
  { iata: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona", country: "ES" },
  { iata: "PMI", name: "Palma de Mallorca Airport", city: "Palma", country: "ES" },
  { iata: "AGP", name: "Málaga-Costa del Sol Airport", city: "Malaga", country: "ES" },
  { iata: "FCO", name: "Leonardo da Vinci International", city: "Rome", country: "IT" },
  { iata: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "IT" },
  { iata: "LIN", name: "Milan Linate Airport", city: "Milan", country: "IT" },
  { iata: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "IT" },
  { iata: "NAP", name: "Naples International Airport", city: "Naples", country: "IT" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "BE" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "DK" },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "SE" },
  { iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "NO" },
  { iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "FI" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "CH" },
  { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "CH" },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "AT" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "PL" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "CZ" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "HU" },
  { iata: "OTP", name: "Henri Coandă International", city: "Bucharest", country: "RO" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "BG" },
  { iata: "ATH", name: "Athens International Airport Eleftherios Venizelos", city: "Athens", country: "GR" },
  { iata: "SKG", name: "Thessaloniki Airport Macedonia", city: "Thessaloniki", country: "GR" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "TR" },
  { iata: "SAW", name: "Istanbul Sabiha Gökçen International", city: "Istanbul", country: "TR" },
  { iata: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "PT" },
  { iata: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "PT" },
  // Asia Pacific
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "JP" },
  { iata: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "JP" },
  { iata: "KIX", name: "Kansai International Airport", city: "Osaka", country: "JP" },
  { iata: "ITM", name: "Osaka Itami Airport", city: "Osaka", country: "JP" },
  { iata: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "JP" },
  { iata: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "JP" },
  { iata: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "JP" },
  { iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "KR" },
  { iata: "GMP", name: "Gimpo International Airport", city: "Seoul", country: "KR" },
  { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "CN" },
  { iata: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "CN" },
  { iata: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "CN" },
  { iata: "SHA", name: "Shanghai Hongqiao International", city: "Shanghai", country: "CN" },
  { iata: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "CN" },
  { iata: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "CN" },
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "HK" },
  { iata: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "TW" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "TH" },
  { iata: "DMK", name: "Don Mueang International", city: "Bangkok", country: "TH" },
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "SG" },
  { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "MY" },
  { iata: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "ID" },
  { iata: "DPS", name: "Ngurah Rai International", city: "Bali", country: "ID" },
  { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "PH" },
  { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "VN" },
  { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "VN" },
  { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "VN" },
  { iata: "DEL", name: "Indira Gandhi International", city: "New Delhi", country: "IN" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "IN" },
  { iata: "BLR", name: "Kempegowda International", city: "Bangalore", country: "IN" },
  { iata: "MAA", name: "Chennai International", city: "Chennai", country: "IN" },
  { iata: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "IN" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "IN" },
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "AU" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "AU" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "AU" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "AU" },
  { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "AU" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "NZ" },
  { iata: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "NZ" },
  { iata: "WLG", name: "Wellington Airport", city: "Wellington", country: "NZ" },
  // Middle East & Africa
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "AE" },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "AE" },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "QA" },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "SA" },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "SA" },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "KW" },
  { iata: "BAH", name: "Bahrain International Airport", city: "Manama", country: "BH" },
  { iata: "MCT", name: "Muscat International Airport", city: "Muscat", country: "OM" },
  { iata: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "IL" },
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "EG" },
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "ZA" },
  { iata: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "ZA" },
  { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "KE" },
  { iata: "ADD", name: "Addis Ababa Bole International", city: "Addis Ababa", country: "ET" },
  { iata: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "NG" },
  { iata: "ACC", name: "Kotoka International Airport", city: "Accra", country: "GH" },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "MA" },
  // Latin America
  { iata: "GRU", name: "São Paulo Guarulhos International", city: "São Paulo", country: "BR" },
  { iata: "CGH", name: "São Paulo Congonhas Airport", city: "São Paulo", country: "BR" },
  { iata: "GIG", name: "Rio de Janeiro Galeão International", city: "Rio de Janeiro", country: "BR" },
  { iata: "BSB", name: "Presidente Juscelino Kubitschek International", city: "Brasília", country: "BR" },
  { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "AR" },
  { iata: "AEP", name: "Jorge Newbery Airfield", city: "Buenos Aires", country: "AR" },
  { iata: "SCL", name: "Arturo Merino Benítez International", city: "Santiago", country: "CL" },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "CO" },
  { iata: "MDE", name: "José María Córdova International", city: "Medellín", country: "CO" },
  { iata: "LIM", name: "Jorge Chávez International", city: "Lima", country: "PE" },
  { iata: "MEX", name: "Benito Juárez International Airport", city: "Mexico City", country: "MX" },
  { iata: "CUN", name: "Cancún International Airport", city: "Cancún", country: "MX" },
  { iata: "GDL", name: "Miguel Hidalgo y Costilla International", city: "Guadalajara", country: "MX" },
  { iata: "MTY", name: "General Mariano Escobedo International", city: "Monterrey", country: "MX" },
];

export function searchAirports(query: string, limit = 6): Airport[] {
  const q = query.toUpperCase().trim();
  if (!q) return [];

  // Exact IATA match first
  const exact = AIRPORTS.filter((a) => a.iata === q);
  // Starts-with IATA
  const iataPrefix = AIRPORTS.filter((a) => a.iata !== q && a.iata.startsWith(q));
  // City/name contains
  const qLower = query.toLowerCase();
  const textMatch = AIRPORTS.filter(
    (a) =>
      !a.iata.startsWith(q) &&
      (a.city.toLowerCase().includes(qLower) || a.name.toLowerCase().includes(qLower))
  );

  return [...exact, ...iataPrefix, ...textMatch].slice(0, limit);
}
